import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { HOOK_NAMES } from './event-map';

export const HOOK_COMMAND_MARKER = 'cctint hook';

// Claude Code hook format: each hook event holds an array of HookGroupEntry.
// Each entry has an optional matcher (tool name filter, empty = all tools)
// and a hooks array containing the actual commands.
interface HookCommand {
  type: 'command';
  command: string;
}

interface HookGroupEntry {
  matcher: string;
  hooks: HookCommand[];
}

interface Settings {
  hooks?: Record<string, unknown[]>;
  [k: string]: unknown;
}

export interface RegisterHooksOptions {
  binPath: string;
}

export function registerHooks(settingsFile: string, opts: RegisterHooksOptions): void {
  const parsed = readSettingsResult(settingsFile);
  if (parsed.kind === 'invalid') {
    throw new Error(
      `refusing to modify ${settingsFile}: invalid JSON or root is not an object — fix the file, then run cctint install again`,
    );
  }
  const settings = parsed.kind === 'ok' ? parsed.settings : {};
  settings.hooks = settings.hooks ?? {};
  for (const hook of HOOK_NAMES) {
    const entries = settings.hooks[hook] ?? [];
    const filtered = entries.filter((e) => !isCctintEntry(e));
    const newEntry: HookGroupEntry = {
      matcher: '',
      hooks: [{ type: 'command', command: `${opts.binPath} hook ${hook}` }],
    };
    filtered.push(newEntry);
    settings.hooks[hook] = filtered;
  }
  writeSettings(settingsFile, settings);
}

export function unregisterHooks(settingsFile: string): void {
  if (!existsSync(settingsFile)) return;
  const parsed = readSettingsResult(settingsFile);
  if (parsed.kind !== 'ok') {
    // Corrupt or non-object JSON: do not write — overwriting would wipe the file.
    return;
  }
  const settings = parsed.settings;
  if (!settings.hooks) {
    writeSettings(settingsFile, settings);
    return;
  }
  for (const hook of Object.keys(settings.hooks)) {
    const remaining = (settings.hooks[hook] ?? []).filter((e) => !isCctintEntry(e));
    if (remaining.length === 0) {
      delete settings.hooks[hook];
    } else {
      settings.hooks[hook] = remaining;
    }
  }
  if (Object.keys(settings.hooks).length === 0) {
    delete settings.hooks;
  }
  writeSettings(settingsFile, settings);
}

/**
 * Detects cctint entries in both the current format {matcher, hooks: [{command}]}
 * and the legacy flat format {type, command} so unregisterHooks cleans up both.
 */
function isCctintEntry(e: unknown): boolean {
  if (typeof e !== 'object' || e === null) return false;
  const obj = e as Record<string, unknown>;
  // Current format: {matcher, hooks: [{type, command}]}
  if (Array.isArray(obj.hooks)) {
    return obj.hooks.some(
      (h: unknown) =>
        typeof h === 'object' &&
        h !== null &&
        typeof (h as Record<string, unknown>).command === 'string' &&
        ((h as Record<string, unknown>).command as string).includes(HOOK_COMMAND_MARKER),
    );
  }
  // Legacy flat format: {type, command} — generated by earlier versions of cctint
  return typeof obj.command === 'string' && (obj.command as string).includes(HOOK_COMMAND_MARKER);
}

type ReadSettingsResult =
  | { kind: 'missing' }
  | { kind: 'ok'; settings: Settings }
  | { kind: 'invalid' };

function readSettingsResult(path: string): ReadSettingsResult {
  if (!existsSync(path)) return { kind: 'missing' };
  const raw = readFileSync(path, 'utf8');
  try {
    const parsed = JSON.parse(raw);
    if (typeof parsed === 'object' && parsed !== null && !Array.isArray(parsed)) {
      return { kind: 'ok', settings: parsed as Settings };
    }
    return { kind: 'invalid' };
  } catch {
    return { kind: 'invalid' };
  }
}

function writeSettings(path: string, settings: Settings): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, JSON.stringify(settings, null, 2) + '\n', 'utf8');
}
